---

- hosts: localhost
  
  roles:
    - { role: symfony3 }
    - { role: php_codesniffer }

  tasks:
  - name: remove composer cache.
    file:
      path: '/home/vagrant/.composer/cache'
      state: absent