---

- name: Add repository key for Elastic Search repository.
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Add repository for Elastic Search.
  apt_repository: repo='deb https://artifacts.elastic.co/packages/6.x/apt stable main' state=present

- name: Allocate Elastic Search resources.
  template: 
    src: '99-elastic.conf.j2'
    dest: '/etc/sysctl.d/99-elastic.conf'
    owner: root
    group: root

- name: Pin Elastic Search packages.
  template:
    src: elastic.pref.j2
    dest: "/etc/apt/preferences.d/elastic.pref"
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Update apt cache.
  apt:
    update_cache: yes

- name: Ensure Elastic Search is installed.
  apt:
    pkg: "elasticsearch"
    state: present

- name: Configure Elastic Search.
  template: 
    src: 'elasticsearch.yml.j2'
    dest: '/etc/elasticsearch/elasticsearch.yml'
    owner: root
    group: elasticsearch
    mode: 0660
    force: yes

- name: Copy startup script in place.
  template:
    src: startup.sh.j2
    dest: "/opt/run-parts/elastic"
    owner: root
    group: root
    mode: 0555
    force: yes

- name: Copy landing page section.
  template:
    src: "section.html.j2"
    dest: "{{ ce_vm_webroot }}/includes/elastic.html"
    force: yes
