---
# Install mysql

- name: Add repository key for MySQL repository.
  apt_key: keyserver=pgp.mit.edu id=A4A9406876FCBD3C456770C88C718D3B5072E1F5 state=present
  when: mysql_engine == "mysql"

- name: Add repository for MySQL.
  apt_repository: repo='deb http://repo.mysql.com/apt/debian/ jessie mysql-5.7' state=present
  when: mysql_engine == "mysql"

- name: Add source repository for MySQL.
  apt_repository: repo='deb-src http://repo.mysql.com/apt/debian/ jessie mysql-5.7' state=present
  when: mysql_engine == "mysql"
  
- name: Pin MySQL packages.
  template:
    src: mysql.pref.j2
    dest: "/etc/apt/preferences.d/mysql.pref"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: mysql_engine == "mysql"
  
- name: Ensure mysql is installed.
  apt:
    pkg: "{{ mysql_engine }}-server"
    state: present

- name: Copy MySQL overriding configuration in place.
  template:
    src: mysql_dev.cnf.j2
    dest: "/etc/mysql/mysql.conf.d/zz_dev.cnf"
    owner: root
    group: root
    mode: 0644
    force: yes
  when: mysql_engine == "mysql"
  
- name: Ensure python-mysqldb is installed.
  apt:
    pkg: "python-mysqldb"
    state: present