---

- hosts: localhost
  
  roles:
    - { role: php-cli, php_version: 5.6 }
    - { role: php-cli, php_version: 7.0 }
    - { role: php-cli, php_version: 7.1 }
    - { role: php-cli, php_version: 7.2 }
    - { role: php-cli, php_version: 7.3 }
    - { role: php-cli, php_version: 7.4 }
    - { role: composer }
    - { role: messdetector }
    
  tasks:
  - name: remove composer cache.
    file:
      path: '/home/vagrant/.composer/cache'
      state: absent

  - name: Ensure mysql-client is installed.
    apt:
      pkg: mysql-client
      state: present
