---

- hosts: localhost
  
  roles:
    - { role: php-fpm, php_version: 5.6 }
    - { role: php-fpm, php_version: 7.0 }
    - { role: php-fpm, php_version: 7.1 }
    - { role: php-fpm, php_version: 7.2 }
    - { role: php-fpm, php_version: 7.3 }
    - { role: php-fpm, php_version: 7.4 }