---

- hosts: localhost
  
  roles:
    - { role: nodejs, nodejs_version: 8.x }
    - { role: yarn }
    
  tasks:
  - name: remove composer cache.
    file:
      path: '/home/vagrant/.composer/cache'
      state: absent