---
# Install Yarn

- name: Add repository key for Yarn repository.
  apt_key: url=https://dl.yarnpkg.com/debian/pubkey.gpg state=present
  
- name: Add repository for Yarn.
  apt_repository: repo='deb https://dl.yarnpkg.com/debian/ stable main' state=present

- name: Update apt cache.
  apt:
    update_cache: yes

- name: Ensure Yarn is installed.
  apt:
    pkg: "yarn"
    state: present