---

- name: Update apt cache.
  apt:
    update_cache: yes
    allow_unauthenticated: yes

- name: Install JDK packages.
  apt: 
    name: "{{ item }}" 
    state: present
    allow_unauthenticated: yes
  with_items:
    - "openjdk-8-jre"
    - "openjdk-8-jdk"
 
- name: Install Sonar
  apt:
   deb: https://freefr.dl.sourceforge.net/project/sonar-pkg/deb/binary/sonar_7.1_all.deb

- name: Allocate Elastic Search resources.
  template: 
    src: '99-sonar.conf.j2'
    dest: '/etc/sysctl.d/99-sonar.conf'
    owner: root
    group: root

- name: install Sonar Scanner
  unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
    dest: /opt/
    remote_src: yes

- name: add Sonar Scanner to bin paths.
  file:
    src: "/opt/sonar-scanner-3.2.0.1227-linux/bin/sonar-scanner"
    dest: "/usr/local/bin/sonar-scanner"
    state: link