---
# Install Redis

- name: Add repository key for Dotdeb.
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg state=present
  
- name: Add repository for Dotdeb.
  apt_repository: repo='deb http://packages.dotdeb.org stretch all' state=present

- name: Add source repository for Dotdeb.
  apt_repository: repo='deb-src http://packages.dotdeb.org stretch all' state=present

- name: Pin Dotdeb packages.
  template:
    src: dotdeb.pref.j2
    dest: "/etc/apt/preferences.d/redis.pref"
    owner: root
    group: root
    mode: 0644
    force: yes
  
- name: Ensure Redis is installed.
  apt:
    pkg: "redis-server"
    state: present